name: Build master

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use .NET Core 9.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build
      if: runner.os != 'Windows'
      run: |
        dotnet run bundle
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        # DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        CI: true
    - name: Build
      if: runner.os == 'Windows'
      run: |
        dotnet run bundle
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        # DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        CI: true
